// client/home/dashboard.svelte
<!--
  Copyright (C) 2018  Akihiko Odaki <nekomanma@pixiv.co.jp>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

<h1>{{$sessionUsername}}</h1>
<form on:submit='post(event)'>
  <textarea name='text' />
  <button>Post</button>
</form>
<script>
  export default {
    oncreate() {
      this.store.stream();
    },

    methods: {
      post(event) {
        event.preventDefault();
        this.store.createNote(event.target.elements.text.value);
      }
    }
  };
</script>

// client/subscribers/react/components/dashboard.js
/*
  Copyright (C) 2018  Akihiko Odaki <nekomanma@pixiv.co.jp>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import React from 'react';
import { connect } from 'react-redux';
import { noteCreation } from '../../../actions/notes';
import { open as streamingOpen } from '../../../actions/streaming';

export default connect(state => ({
  username: state.session.username
}))(class extends React.PureComponent {
  componentWillMount() {
    this.props.dispatch(streamingOpen());

    this.post = event => {
      event.preventDefault();
      this.props.dispatch(noteCreation(event.target.elements.text.value));
    };
  }

  render() {
    return (
      <div>
        {this.props.username}
        <form onSubmit={this.post}>
          <textarea name='text' />
          <button>Post</button>
        </form>
      </div>
    );
  }
});
